name: kaia_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Ícones e fontes
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  material_symbols_icons: ^4.2874.0

  # Gerenciamento de estado e injeção de dependência
  provider: ^6.1.5+1
  get_it: ^8.2.0

  # HTTP e serialização
  dio: ^5.9.0
  http: ^1.5.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0 # Armazenamento seguro de tokens

  # Internacionalização (datas e moedas)
  intl: ^0.18.1

  # Upload e manipulação de imagem
  image_picker: ^1.1.1

  # Abrir e baixar arquivos/links
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints e geração de código
  flutter_lints: ^6.0.0
  build_runner: ^2.9.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true

  # Descomente e adicione seus assets quando necessário
  # assets:
  #   - assets/images/

  # Descomente se quiser adicionar fontes personalizadas
  # fonts:
  #   - family: YourFont
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
